spring:
  config:
    activate:
      on-profile: dev

# server.port 등은 jobstat-api-gateway.yml의 기본값을 따름

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_GATEWAY_DEV:${EUREKA_INSTANCE_HOSTNAME_GATEWAY:localhost}}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS_GATEWAY_DEV:${EUREKA_INSTANCE_PREFER_IP_ADDRESS_GATEWAY:false}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_GATEWAY_DEV:${EUREKA_DEFAULT_ZONE_GATEWAY:http://localhost:8761/eureka/}}
