server:
  port: ${GATEWAY_PORT:8000}

spring:
  application:
    name: jobstat-api-gateway
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_GATEWAY:localhost} # dev 기본 localhost
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS_GATEWAY:false} # dev 기본 false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_GATEWAY:http://localhost:8761/eureka/} # dev 기본 로컬 Eureka

# JWT 검증을 위한 설정 (core_token 모듈의 JwtTokenParser가 사용)
jobstat:
  core:
    security:
      admin:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
    token:
      jwt:
        secret: ${JWT_SECRET}
        access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION:900}
        refresh-token-expiration-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}
        tokenPrefix: "Bearer "
    error:
      global-handler:
        enabled: true # 전역 에러 핸들러 사용

# 로깅 레벨 (Gateway 디버깅 시 유용)
logging:
  level:
    root: DEBUG # 기본 로깅 레벨
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG # HTTP 클라이언트 상세 로깅
    com.wildrew.apigateway: DEBUG # Gateway 자체 코드 로깅
