spring:
  config:
    activate:
      on-profile: prod

# server.port 등은 jobstat-api-gateway.yml의 기본값을 따름 (환경 변수로 제어)

eureka:
  instance:
    hostname: jobstat-api-gateway-service # 쿠버네티스 내부 서비스 이름
    prefer-ip-address: true # 쿠버네티스 환경에서는 IP 주소 선호
  client:
    serviceUrl:
      defaultZone: http://jobstat-eureka-server:8761/eureka/ # 쿠버네티스 내부 Eureka 서비스 이름