spring:
  config:
    activate:
      on-profile: dev

# server.port 등은 jobstat-api-gateway.yml의 기본값을 따름

eureka:
  instance:
    hostname: jobstat-api-gateway-service
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
