spring:
  application:
    name: jobstat-eureka-server
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://jobstat-config-server:8888}"
  profiles:
    active: ${APP_PROFILE:dev}

