version: '3.8'

networks:
  public:
    name: public           # 실제 Docker 네트워크 이름을 'public'으로 사용
    external: false        # 없으면 새로 만든다(Compose가 직접 관리)
  internal:
    name: internal         # 실제 Docker 네트워크 이름을 'internal'
    driver: bridge
    internal: true         # 외부 라우팅 차단(내부 전용)
    external: false        # 없으면 만들고, 있으면 재사용

services:
  nginx:
    container_name: nginx
    image: ${DOCKERHUB_USERNAME}/jobstat-nginx:${BACKEND_TAG}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '256M'
        reservations:
          cpus: '0.25'
          memory: '128M'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    networks:
      - public     # 외부와 통신
      - internal   # 내부 서비스와 통신
    depends_on:
      spring-app:
        condition: service_healthy
    restart: always

  spring-app:
    container_name: spring-app
    image: ${DOCKERHUB_USERNAME}/jobstat-app:${BACKEND_TAG}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1G'
        reservations:
          cpus: '0.5'
          memory: '512M'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_NAME=prod_jobstat
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION=999999
      - JWT_REFRESH_TOKEN_EXPIRATION=604800
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=27017
      - MONGO_DB=prod_database
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_DB=1
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DDNS_DOMAIN=${DDNS_DOMAIN}
      - GMAIL_ID=${GMAIL_ID}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
    networks:
      - public
      - internal
    expose:
      - "8081"
    restart: always

volumes:
  nginx-logs: