version: '3.8'

networks:
  web:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: ${DOCKERHUB_USERNAME}/jobstat-nginx:${BACKEND_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    networks:
      - web
    depends_on:
      - spring-app
    restart: always

  spring-app:
    container_name: spring-app
    image: ${DOCKERHUB_USERNAME}/jobstat-app:${BACKEND_TAG}
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_NAME=dev_jobstat
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION=999999
      - JWT_REFRESH_TOKEN_EXPIRATION=604800
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=27017
      - MONGO_DB=dev_database
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_DB=1
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    networks:
      - web
    expose:
      - "8081"
    restart: always

  frontend:
    container_name: frontend
    image: ${DOCKERHUB_USERNAME}/jobstat-frontend:latest
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://spring-app:8081
    networks:
      - web
    expose:
      - "3000"
    depends_on:
      - spring-app
    restart: always

volumes:
  nginx-logs: