version: '3.8'

services:

  nginx:
    image: ${DOCKERHUB_USERNAME}/jobstat-nginx:${TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    depends_on:
      - spring-app
    restart: always

  spring-app:
    image: ${DOCKERHUB_USERNAME}/jobstat-app:${TAG}
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=dev
      - DB_HOST=${DB_HOST}  # 로컬 PC의 IP
      - DB_PORT=3306
      - DB_NAME=dev_jobstat
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION=999999
      - JWT_REFRESH_TOKEN_EXPIRATION=604800
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}  # 로컬 PC의 IP
      - MONGO_PORT=27017
      - MONGO_DB=dev_database
      - REDIS_HOST=${REDIS_HOST}  # 로컬 PC의 IP
      - REDIS_PORT=6379
      - REDIS_DB=1
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_DSN=${SENTRY_DSN}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    ports:
      - "8081:8081"
    restart: always

volumes:
  nginx-logs: