app:
  server:
    url: http://localhost:8081

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dev_jobstat}?
      serverTimezone=UTC&useSSL=false
      &allowPublicKeyRetrieval=true
      &rewriteBatchedStatements=true
      &useServerPrepStmts=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      initialization-fail-timeout: 30000
      connection-init-sql: "SET sql_mode='NO_ENGINE_SUBSTITUTION'"
      cache-prepared-statements: true
      prepared-statement-cache-size: 250
      prepared-statement-cache-sql-limit: 2048


  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:dev_database}?maxPoolSize=5&minPoolSize=2&maxIdleTimeMS=30000
      database: ${MONGO_DB:dev_database}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1}
      password: ${REDIS_PASSWORD}
      username: default
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
      client-type: lettuce
      connect-timeout: 5000
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
    chunk-size: 1000
    max-threads: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        connection.provider_disables_autocommit: false
        acquire_increment: 1
        acquire_retry_attempts: 3
        acquire_retry_delay: 5000


batch:
  chunk-size: 500
  job-size: 100

