ddns.domain: ${DDNS_DOMAIN}

server:
  tomcat:
    threads:
      max: 50
      min-spare: 10
    max-connections: 10000
    accept-count: 100
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 2048
  http2:
    enabled: true
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: NATIVE

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: false
  application:
    name: jobstat
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: false
  cache:
    type: caffeine

logging:
  level:
    root: INFO
    com.example: DEBUG
    org:
      springframework:
        security=DEBUG:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  config: classpath:logback-spring.xml
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}

monitoring:
  cpu:
    threshold: 80.0
    check-interval: 30000
    debug-duration: 1800000  # 30분

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: ${JWT_ACCESS_TOKEN_EXPIRATION:999999}
  refreshTokenExpiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}
  tokenPrefix: "Bearer "

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:3000,http://localhost:8080"}
  security:
    public-paths:
      - "/api/auth/**"
      - "/api/token/refresh"
      - "/api/public/**"
  cache:
    ttl: ${CACHE_TTL:600}
  mongodb:
    page-size: ${MONGODB_PAGE_SIZE:20}


admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}