spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:prod_jobstat}?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:prod_database}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:2}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SENTRY_ENV:production}
  release: ${SENTRY_RELEASE:"1.0.0"}
  traces-sample-rate: ${SENTRY_SAMPLE_RATE:1.0}
  logging:
    minimum-event-level: ${SENTRY_MIN_EVENT_LEVEL:error}
    minimum-breadcrumb-level: ${SENTRY_MIN_BREADCRUMB_LEVEL:info}
  in-app-includes: ${SENTRY_IN_APP_INCLUDES:com.example.jobstat}
  exception-resolver-order: ${SENTRY_EXCEPTION_RESOLVER_ORDER:-2147483647}
  enable-tracing: ${SENTRY_ENABLE_TRACING:true}