spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://host.k3d.internal:3306/prod_jobstat?serverTimezone=Asia/Seoul&useSSL=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&useServerPrepStmts=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      initialization-fail-timeout: 30000
      connection-init-sql: "SET sql_mode='NO_ENGINE_SUBSTITUTION'"
    redis:
      host: host.k3d.internal
      port: 6379
      database: 2
      password: ${REDIS_PASSWORD}
      username: default
      client-type: lettuce
      connect-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.wildrew.app.community: INFO
    org.hibernate: WARN
    org.springframework.kafka: WARN
    org.springframework.transaction: WARN

jobstat:
  core:
    openapi:
      title: "JobStat Community API (Production)"
      server:
        urls: "https://community.jobstat.com"
        description: "Community Production Server"

eureka:
  instance:
    hostname: jobstat-community-service # 쿠버네티스 내부 서비스 이름
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://jobstat-eureka-server:8761/eureka/ # 쿠버네티스 내부 Eureka 서비스 이름

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false