spring:
  application:
    name: jobstat-community-read
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://config-server-service:8888}

  config:
    import: "optional:configserver:"

  profiles:
    active: ${APP_PROFILE:dev}
