server:
  port: 8086
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 2048
  http2:
    enabled: true
  forward-headers-strategy: NATIVE

spring:
  application:
    name: jobstat-notification
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: caffeine #
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1}
      password: ${REDIS_PASSWORD}
      username: default
      lettuce:
        pool:
          max-active: 8
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_NOTIFICATION:localhost}
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_NOTIFICATION:http://localhost:8761/eureka/}

logging:
  level:
    root: WARN
    com.wildrew: INFO
    org.springframework: WARN
    org.hibernate: WARN
    org.springframework.kafka: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env,configprops,loggers,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true

jobstat: # 애플리케이션 특정 설정 네임스페이스
  core:
    security:
      admin: # 관리자 계정 정보 (필요시 사용)
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
    openapi: # OpenAPI (Swagger) 문서 설정
      title: "JobStat Notification API"
      version: "v1.0-notification"
      description: "JobStat 알림 서비스 API 문서"
      server:
        urls: "http://localhost:${server.port}"
        description: "알림 서비스"
      security:
        bearer-auth:
          enabled: false
      custom-model-converter:
        enabled: true
    error:
      global-handler:
        enabled: true
    event:
      dlt:
        consumer: # DLT 소비자 설정
          enabled: true # 알림 서비스가 DLT를 소비할 경우 활성화
          topic-pattern: "${spring.kafka.consumer.notification.topic:notification-unknown}${spring.kafka.consumer.common.dlt-suffix:.DLT}"
          group-id: "${spring.application.name}-dlt-consumer-group-${spring.profiles.active:dev}"


springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
  default-models-expand-depth: 1
  default-produces-media-type: application/json