spring:
  threads:
    virtual:
      enabled: true
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:batch}
      auto-index-creation: true
      connect-timeout: 5000
      socket-timeout: 5000
      server-selection-timeout: 5000
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:2}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    chunk-size: 1000
    job-queue-size: 100
    max-threads: 5


batch:
  chunk-size: 2000
  small-size: 100
  job-size: 100

logging:
  level:
    root: INFO
    com.wildrew.batch: DEBUG
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.testcontainers: INFO