server:
  port: 8085

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:dev_database}?maxPoolSize=5&minPoolSize=2&maxIdleTimeMS=30000
      database: ${MONGO_DB:dev_database}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1}
      password: ${REDIS_PASSWORD}
      username: default
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
      client-type: lettuce
      connect-timeout: 5000

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_STATS_READ_DEV:localhost}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_STATS_READ_DEV:http://localhost:8761/eureka/}

logging:
  level:
    com.wildrew.app.statistics_read: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG

jobstat:
  core:
    openapi:
      title: "JobStat Statistics Read API (Development)"
      server:
        urls: "http://localhost:${server.port}"
        description: "Statistics Read Development Server"
      security:
        bearer-auth:
          enabled: false

springdoc:
  security:
    bearer-auth:
      enabled: false
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    default-models-expand-depth: 1
  default-produces-media-type: application/json