server:
  port: 8085
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 2048
  http2:
    enabled: true
  forward-headers-strategy: NATIVE


spring:
  application:
    name: jobstat-statistics-read
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  cache:
    type: caffeine
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1}
      password: ${REDIS_PASSWORD}
      username: default
      lettuce:
        pool:
          max-active: 8
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_STATS_READ:localhost}
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_STATS_READ:http://localhost:8761/eureka/}

logging:
  level:
    root: WARN
    com.wildrew: INFO
    org.springframework: WARN
    org.springframework.data.mongodb.core: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env,configprops
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true

jobstat:
  core:
    security:
      admin:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
    openapi:
      title: "JobStat Statistics Read API"
      version: "v1.0-statistics-read"
      description: "JobStat Statistics Read Service API Documentation"
      server:
        urls: "http://localhost:${server.port}"
        description: "Statistics Read Service"
      security:
        bearer-auth:
          enabled: false
      custom-model-converter:
        enabled: true
    error:
      global-handler:
        enabled: true

  statistics-read:
    mongodb:
      page-size: ${MONGODB_PAGE_SIZE:100}
    cache:
      stats-document:
        size: ${STATS_DOCUMENT_CACHE_SIZE:50000}
        expire-after-access-days: ${STATS_DOCUMENT_CACHE_EXPIRE_DAYS:1}
      ranking-cache:
        size: ${RANKING_CACHE_SIZE:100}
        expire-after-access-days: ${RANKING_CACHE_EXPIRE_DAYS:1}


springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
  default-models-expand-depth: 1
  default-produces-media-type: application/json