server:
  port: ${STATISTICS_READ_PORT:8085}

spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:prod_database}?maxPoolSize=5&minPoolSize=2&maxIdleTimeMS=30000
      database: ${MONGO_DB:dev_database}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1}
      password: ${REDIS_PASSWORD}
      username: default
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
      client-type: lettuce
      connect-timeout: 5000

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_STATS_READ_PROD:statistics-read-service}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_STATS_READ_PROD:http://jobstat-eureka-server:8761/eureka/}

logging:
  level:
    com.wildrew.app.statistics_read: INFO
    org.springframework.data.mongodb.core: WARN
    org.mongodb.driver: WARN

jobstat:
  core:
    openapi:
      title: "JobStat Statistics Read API (Production)"
      server:
        urls: "https://statistics.jobstat.com" # 실제 운영 도메인
        description: "Statistics Read Production Server"
      security:
        bearer-auth:
          enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false