spring:
  application:
    name: jobstat-notification
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://jobstat-config-server:8888}"
