# file: .../jobstat-auth/src/main/resources/application.yml
spring:
  application:
    name: jobstat-auth
  profiles:
    active: ${APP_PROFILE:dev}
  config:
    import: "optional:configserver:"

---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: host.k3d.internal

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server-service:8888}