spring:
  application:
    name: jobstat-api-gateway
  profiles:
    active: ${APP_PROFILE:dev}
  config:
    import: "optional:configserver:"


# spring bean 주입 체크 로깅추가
logging:
  level:
      org.springframework.beans.factory.annotation.Autowired: DEBUG
      org.springframework.beans.factory.annotation.Value: DEBUG
---

spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      uri: http://localhost:8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: host.k3d.internal

---

spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server-service:8888}