spring:
  application:
    name: jobstat-api-gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"
  profiles:
    active: ${APP_PROFILE:dev} # 로컬 실행 시 프로파일
