spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:prod_jobstat}?
      serverTimezone=Asia/Seoul&useSSL=true
      &allowPublicKeyRetrieval=true
      &rewriteBatchedStatements=true
      &useServerPrepStmts=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      initialization-fail-timeout: 30000
      connection-init-sql: "SET sql_mode='NO_ENGINE_SUBSTITUTION'"
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:2}
      password: ${REDIS_PASSWORD}
      username: default
      client-type: lettuce
      connect-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.wildrew: INFO
    org.hibernate: WARN
    org.springframework.security: WARN

jobstat:
  core:
    openapi:
      title: "JobStat Auth API (Production)"
      server:
        urls: "https://auth.jobstat.com"
        description: "Auth Production Server"

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_AUTH_PROD:jobstat-auth-service}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_AUTH_PROD:http://jobstat-eureka-server:8761/eureka/}

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false