server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain
    min-response-size: 2048
  http2:
    enabled: true
  forward-headers-strategy: NATIVE

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
#    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    prefer-ip-address: false
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

spring:
  application:
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  h2:
    console:
      enabled: false
  cache:
    type: caffeine
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env,configprops
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: WARN
    com.wildrew: INFO
    org.springframework: WARN
    org.hibernate: WARN

springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
  default-models-expand-depth: 1
  default-produces-media-type: application/json

kafka:
  consumer:
    common:
      dlt-suffix: .DLT
      auto-create-dlt: true


ddns.domain: ${DDNS_DOMAIN}
SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}

