server:
  port: 8081

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_JOBSTAT:localhost}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_JOBSTAT:http://localhost:8761/eureka/}

spring:
  application:
    name: jobstat
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ID}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      add-mappings: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: false
  cache:
    type: caffeine
#  datasource:
#    url: ${JDBC_URL:jdbc:mysql://localhost:3306/jobstat?serverTimezone=Asia/Seoul}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1} # 또는 직접 숫자 (예: 1)
      password: ${REDIS_PASSWORD}
      username: default # Lettuce에서 username 설정이 필요하다면 명시
      lettuce: # Lettuce 관련 상세 설정 (선택적)
        pool:
          max-active: 8

logging:
  debug: true
  level:
    root: WARN
    com.wildrew: WARN
    org:
      springframework:
        security: WARN
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: WARN

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      access: read_only
  prometheus:
    metrics:
      export:
        enabled: true

monitoring:
  cpu:
    threshold: 80.0
    check-interval: 30000
    debug-duration: 1800000 # 30분

jobstat:
  core:
    security:
      admin:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
    token:
      jwt:
        secret: ${JWT_SECRET}
        access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION:999999}
        refresh-token-expiration-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION:9604800}
        tokenPrefix: "Bearer "
    openapi:
      title: "JobStat API (Default)"
      version: "v1.0-default"
      description: "JobStat API Documentation"
      server:
        urls: "http://localhost:${server.port:8081}" # 현재 서버 포트를 기본값으로 사용
        description: "Current Development Server"
      security:
        bearer-auth:
          enabled: true # JWT 보안 기본 활성화
      custom-model-converter:
        enabled: true # com.wildrew.jobstat.core.core_open_api.CustomModelConverter 기본 활성화
    error:
      global-handler:
        enabled: true


  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:3000,http://localhost:8080"}
  security:
    public-paths:
      - "/api/auth/**"
      - "/api/token/refresh"
      - "/api/public/**"
  cache:
    ttl: ${CACHE_TTL:600}
  mongodb:
    page-size: ${MONGODB_PAGE_SIZE:20}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

counter:
  like-reset-hour: 0
  user-action-ttl-seconds: 86400
  flush-interval-seconds: 300
  flush-interval-milliseconds: 10000
  view-count-cache-ttl-seconds: 60
  view-count-sync-interval: 60000

cache:
  board:
    detail:
      ttl-seconds: 3600
    list:
      ttl-seconds: 300
    popular:
      ttl-seconds: 600
    count:
      ttl-seconds: 1800

outbox:
  relay:
    kafka-send-timeout-seconds: 3
    scheduler:
      fixed-delay-seconds: 10
      initial-delay-seconds: 5
      cutoff-seconds: 10
      batch-size: 100
    max-retry-count: 3

  processor:
    kafka-send-timeout-seconds: 5
    max-retry-count: 3

dlt:
  consumer:
    group-id: dlt-persistence-group-${spring.profiles.active:dev}


kafka:
  consumer:
    community-read:
      topic: community-read-${spring.profiles.active:dev}
      group-id: community-read-consumer-group-${spring.profiles.active:dev}
      retry:
        attempts: 3
        delay-ms: 1000
        multiplier: 2.0
    community-command:
      topic: community-command-${spring.profiles.active:dev}
      group-id: community-command-consumer-group-${spring.profiles.active:dev}
      retry:
        attempts: 3
        delay-ms: 1000
        multiplier: 2.0
    notification:
      topic: notification-${spring.profiles.active:dev}
      group-id: notification-consumer-group-${spring.profiles.active:dev}
      retry:
        attempts: 3
        delay-ms: 1000
        multiplier: 2.0