spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dev_jobstat}?
      serverTimezone=Asia/Seoul&useSSL=false
      &allowPublicKeyRetrieval=true
      &rewriteBatchedStatements=true
      &useServerPrepStmts=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password} # 실제 개발 환경 비밀번호 사용
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      initialization-fail-timeout: 30000
      connection-init-sql: "SET sql_mode='NO_ENGINE_SUBSTITUTION'"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:1}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # 개발 시에는 스키마 자동 업데이트
    show-sql: true # SQL 쿼리 로깅 활성화 (디버깅용)
    properties:
      hibernate:
        format_sql: true # SQL 가독성 향상

logging:
  level:
    com.wildrew: DEBUG # 개발 시 auth-service 패키지 로그 레벨 DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 파라미터 값까지 로깅
    org.springframework.security: DEBUG

jobstat:
  core:
    openapi:
      title: "JobStat Auth API (Development)"
      server:
        urls: "http://localhost:${server.port:8081}" # jobstat-auth.yml의 server.port 값 참조
        description: "Auth Development Server"

# 개발 환경에서 Eureka 서버 주소가 다르다면 여기에 명시
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://dev-eureka-server:8761/eureka/