server:
  port: 8761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME_EUREKA:localhost}
    prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_EUREKA:http://${eureka.instance.hostname}:${server.port}/eureka/}
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env,configprops
  endpoint:
    health:
      show-details: always