server:
  port: 8888
spring:
  application:
    name: jobstat-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          search-paths:
            - .
            - '{application}'
