name: PR Check

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # Gradle 캐시를 명시적으로 저장
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 다운로드 속도 개선을 위한 미러 설정
      - name: Setup Gradle
        run: |
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties

      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck --no-daemon --build-cache

#      - name: Check Internal Modifier
#        run: ./gradlew checkInternalModifier --no-daemon --build-cache

      - name: Run Tests
        run: ./gradlew test --no-daemon --build-cache
        env:
          SPRING_PROFILES_ACTIVE: test
          TESTCONTAINERS_REUSE_ENABLE: true

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon --build-cache
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DDNS_DOMAIN: ${{ secrets.DDNS_DOMAIN }}
          GMAIL_ID: ${{ secrets.GMAIL_ID }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
